In [1]:
import pandas as pd

In [2]:
s=pd.read_csv("dataset_study.csv")
s

      student_id  study_hours  grade
0              1         9.15  91.91
1              2         9.37  86.81
2              3         2.86  53.39
3              4         8.30  85.52
4              5         6.42  77.98
...          ...          ...    ...
4995        4996         4.89  58.91
4996        4997         4.43  65.22
4997        4998         9.91  81.11
4998        4999         6.91  73.79
4999        5000         0.54  55.08

[5000 rows x 3 columns]

In [3]:
s=s.drop("student_id",axis="columns")
s

      study_hours  grade
0            9.15  91.91
1            9.37  86.81
2            2.86  53.39
3            8.30  85.52
4            6.42  77.98
...           ...    ...
4995         4.89  58.91
4996         4.43  65.22
4997         9.91  81.11
4998         6.91  73.79
4999         0.54  55.08

[5000 rows x 2 columns]

In [4]:
s.isnull().sum()

study_hours    0
grade          0
dtype: int64

In [5]:
#data exploration
s.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   study_hours  5000 non-null   float64
 1   grade        5000 non-null   float64
dtypes: float64(2)
memory usage: 78.3 KB

In [6]:
s.describe()

       study_hours        grade
count  5000.000000  5000.000000
mean      5.031654    64.969712
std       2.910579    17.657329
min       0.000000    15.520000
25%       2.520000    51.717500
50%       5.050000    64.975000
75%       7.582500    78.710000
max      10.000000   100.000000

In [7]:
#feature engineering
import numpy as np
x=s[["study_hours"]]
y=s["grade"]
x

      study_hours
0            9.15
1            9.37
2            2.86
3            8.30
4            6.42
...           ...
4995         4.89
4996         4.43
4997         9.91
4998         6.91
4999         0.54

[5000 rows x 1 columns]

In [8]:
y

0       91.91
1       86.81
2       53.39
3       85.52
4       77.98
        ...
4995    58.91
4996    65.22
4997    81.11
4998    73.79
4999    55.08
Name: grade, Length: 5000, dtype: float64

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=42)
x_train

      study_hours
3716         5.55
3779         3.49
135          5.80
4480         8.87
1437         9.58
...           ...
4426         7.85
466          3.21
3092         3.37
3772         0.31
860          9.78

[4500 rows x 1 columns]

In [10]:
x_test

      study_hours
1501         9.55
2586         6.22
2653         9.34
1055         8.23
705          7.06
...           ...
3928         4.47
544          5.63
367          9.25
1612         3.25
3550         9.57

[500 rows x 1 columns]

In [11]:
from sklearn.preprocessing import StandardScaler
k=StandardScaler()
kx_train=k.fit_transform(x_train)
kx_train

array([[ 0.18152883],
       [-0.52657455],
       [ 0.26746371],
       ...,
       [-0.56782329],
       [-1.61966618],
       [ 1.63554694]])

In [12]:
kx_test=k.transform(x_test)
kx_test

array([[ 1.55648686e+00],
       [ 4.11834302e-01],
       [ 1.48430156e+00],
       [ 1.10275071e+00],
       [ 7.00575488e-01],
       [ 8.17446920e-01],
       [ 7.31512043e-01],
       [-1.62210673e-01],
       [-1.27836722e-01],
       [ 8.69007846e-01],
       [ 6.79951117e-01],
       [-1.56123046e+00],
       [ 8.79320031e-01],
       [ 3.19024636e-01],
       [ 4.74704258e-02],
       [-1.62997836e+00],
       [ 1.53586249e+00],
       [-1.03874641e+00],
       [ 2.22777574e-01],
       [ 6.90263302e-01],
       [-1.24842751e+00],
       [-1.55779307e+00],
       [ 9.99628858e-01],
       [ 2.50276734e-01],
       [ 3.25899426e-01],
       [-1.11780650e+00],
       [-5.30011945e-01],
       [-3.54704796e-01],
       [-5.19699759e-01],
       [ 1.34680576e+00],
       [-5.30011945e-01],
       [-9.35624562e-01],
       [ 4.32458673e-01],
       [-1.47529559e+00],
       [-1.01468465e+00],
       [-5.36886735e-01],
       [ 6.93700698e-01],
       [-4.30327488e-01],
       [ 1.07181415e+00],
       [-1.78400804e-02],
       [ 1.38117971e+00],
       [-1.05937078e+00],
       [ 1.14743685e+00],
       [-1.07655776e+00],
       [ 1.49117635e+00],
       [-8.56564476e-01],
       [-1.29311365e+00],
       [ 9.82441883e-01],
       [ 1.54029673e-01],
       [ 1.60117299e+00],
       [ 4.35896068e-01],
       [-7.67192204e-01],
       [ 5.80266660e-01],
       [-8.65879816e-02],
       [-1.12124390e+00],
       [-1.96584624e-01],
       [-1.47529559e+00],
       [-1.32748760e+00],
       [-1.27936407e+00],
       [-4.53392409e-02],
       [-3.84644507e-02],
       [ 6.49014562e-01],
       [-1.96584624e-01],
       [-1.13843087e+00],
       [ 1.52898770e+00],
       [ 1.52898770e+00],
       [ 1.47398938e+00],
       [-8.35940105e-01],
       [ 5.66517080e-01],
       [ 1.40867887e+00],
       [ 1.84966228e-01],
       [ 9.41193142e-01],
       [-1.09030734e+00],
       [ 8.75882636e-01],
       [-1.50966954e+00],
       [-7.80941784e-01],
       [ 1.28837004e+00],
       [ 1.10962550e+00],
       [ 1.98715809e-01],
       [-6.36571192e-01],
       [-2.47148705e-02],
       [ 1.43274064e+00],
       [ 1.35711794e+00],
       [ 9.54942722e-01],
       [ 7.17762463e-01],
       [-7.19068673e-01],
       [-1.69528887e+00],
       [-7.28384014e-02],
       [ 1.04431499e+00],
       [ 1.24712130e+00],
       [ 3.56835981e-01],
       [-3.71891772e-01],
       [-1.62654097e+00],
       [-1.26561449e+00],
       [-6.77819932e-01],
       [-2.48145550e-01],
       [ 5.87141451e-01],
       [ 1.68023308e+00],
       [-1.36873634e+00],
       [-1.71935064e+00],
       [-1.10649747e-01],
       [ 4.15271697e-01],
       [-1.25186491e+00],
       [ 2.60588920e-01],
       [ 4.73707414e-01],
       [-1.09652902e-02],
       [ 1.53929988e+00],
       [ 5.39017920e-01],
       [ 3.91209932e-01],
       [ 2.34086604e-02],
       [-4.47514463e-01],
       [ 1.42586585e+00],
       [ 1.31243181e+00],
       [ 1.12780932e-01],
       [ 1.08556373e+00],
       [ 3.56835981e-01],
       [ 1.47398938e+00],
       [-9.18437587e-01],
       [-1.49248256e+00],
       [ 1.08212634e+00],
       [-6.36571192e-01],
       [ 8.87191666e-02],
       [-6.29696401e-01],
       [ 7.86510364e-01],
       [-1.45467122e+00],
       [-4.33764883e-01],
       [-9.21874982e-01],
       [ 4.46208253e-01],
       [ 1.27805786e+00],
       [ 1.46711459e+00],
       [ 6.21515401e-01],
       [ 8.24321710e-01],
       [-1.06968297e+00],
       [-8.97813216e-01],
       [ 6.11203216e-01],
       [-5.57511105e-01],
       [ 2.98400265e-01],
       [-1.67466450e+00],
       [-1.46842080e+00],
       [ 9.17131377e-01],
       [-7.22506068e-01],
       [ 1.37774231e+00],
       [ 1.45680240e+00],
       [ 1.15087424e+00],
       [ 5.28705735e-01],
       [ 8.99944401e-01],
       [-1.38248592e+00],
       [ 1.44649022e+00],
       [-5.22140310e-02],
       [-1.07212352e-01],
       [ 1.16806122e+00],
       [ 1.40280092e-01],
       [ 6.12200061e-02],
       [-1.45023698e-01],
       [ 4.59957833e-01],
       [ 5.32143130e-01],
       [ 1.54029673e-01],
       [-1.70560106e+00],
       [ 1.19212298e+00],
       [ 7.96822549e-01],
       [-6.53105062e-04],
       [-9.08125402e-01],
       [ 1.04775239e+00],
       [-1.52685651e+00],
       [-6.12509426e-01],
       [-7.36255648e-01],
       [-1.33436239e+00],
       [-1.23811533e+00],
       [-9.94060278e-01],
       [ 1.19556038e+00],
       [-1.93147229e-01],
       [-1.37217373e+00],
       [ 9.99628858e-01],
       [-1.65060274e+00],
       [ 1.40524148e+00],
       [-1.10061953e+00],
       [ 1.31586920e+00],
       [ 5.18393549e-01],
       [-4.61264043e-01],
       [-1.57841744e+00],
       [-1.58529223e+00],
       [-1.10061953e+00],
       [-4.71576229e-01],
       [ 4.25583883e-01],
       [-6.94010063e-02],
       [-1.24842751e+00],
       [-2.03459414e-01],
       [ 8.14009525e-01],
       [ 1.21962214e+00],
       [-4.09050012e-03],
       [ 1.29524483e+00],
       [-1.24399327e-01],
       [ 1.50148854e+00],
       [ 1.45336501e+00],
       [ 9.82441883e-01],
       [ 1.02468747e-01],
       [-1.53373130e+00],
       [-9.49374142e-01],
       [ 1.06837676e+00],
       [-2.55020340e-01],
       [ 8.44946080e-01],
       [ 6.31827586e-01],
       [ 1.03056541e+00],
       [ 1.12780932e-01],
       [ 8.27759105e-01],
       [ 4.29021278e-01],
       [ 9.85879278e-01],
       [-1.70903845e+00],
       [ 9.72129698e-01],
       [-5.98759846e-01],
       [ 1.06837676e+00],
       [-1.70216366e+00],
       [ 1.68023308e+00],
       [-6.19384216e-01],
       [ 1.37430492e+00],
       [-1.51310693e+00],
       [ 7.14325068e-01],
       [ 6.28390191e-01],
       [-2.75644710e-01],
       [ 1.25743349e+00],
       [ 1.41555366e+00],
       [ 1.41899106e+00],
       [ 1.39492929e+00],
       [-9.01250611e-01],
       [-1.27936407e+00],
       [-6.40008587e-01],
       [ 1.65273392e+00],
       [-8.32502710e-01],
       [ 3.46523796e-01],
       [-2.79082105e-01],
       [ 6.69638932e-01],
       [ 1.02712802e+00],
       [-1.58185483e+00],
       [-1.24155272e+00],
       [-5.19699759e-01],
       [ 8.17446920e-01],
       [-3.50270557e-02],
       [-1.30342583e+00],
       [ 5.08081364e-01],
       [-3.58142192e-01],
       [-1.02843423e+00],
       [-8.94375821e-01],
       [-1.15561785e+00],
       [ 6.66201537e-01],
       [-1.96584624e-01],
       [ 1.07868894e+00],
       [ 1.12681248e+00],
       [-1.54060609e+00],
       [ 1.46367719e+00],
       [-4.09050012e-03],
       [-2.51582945e-01],
       [ 7.04012883e-01],
       [-1.06968297e+00],
       [ 5.09078209e-02],
       [ 2.50276734e-01],
       [-9.00253767e-02],
       [-1.19686659e+00],
       [-1.04562120e+00],
       [-1.24399327e-01],
       [-8.18753130e-01],
       [-2.47148705e-02],
       [-1.37217373e+00],
       [-1.31717541e+00],
       [ 7.38386833e-01],
       [ 2.09027994e-01],
       [-1.44435903e+00],
       [ 8.96507006e-01],
       [-9.69001668e-02],
       [-6.02197241e-01],
       [-1.21405356e+00],
       [-9.66561118e-01],
       [ 7.41824228e-01],
       [ 6.14640611e-01],
       [ 1.48773896e+00],
       [-8.60001871e-01],
       [ 2.53714130e-01],
       [-1.07655776e+00],
       [ 5.49330105e-01],
       [ 1.11306290e+00],
       [-8.65879816e-02],
       [ 1.71216648e-01],
       [-5.74698080e-01],
       [ 1.56679904e+00],
       [-1.62997836e+00],
       [ 9.44630537e-01],
       [ 1.67679569e+00],
       [ 1.50836333e+00],
       [ 1.00306625e+00],
       [-1.63341576e+00],
       [-1.25186491e+00],
       [-6.25262162e-02],
       [-1.59904181e+00],
       [ 1.54961207e+00],
       [-1.44092164e+00],
       [-6.53105062e-04],
       [-1.38248592e+00],
       [-5.85010266e-01],
       [-1.33779978e+00],
       [-1.45810861e+00],
       [-1.47873298e+00],
       [ 4.46208253e-01],
       [-1.72278803e+00],
       [-1.22780314e+00],
       [-9.97497673e-01],
       [ 1.30899441e+00],
       [ 5.59642290e-01],
       [ 8.86194821e-01],
       [-7.05319093e-01],
       [-1.66091492e+00],
       [ 1.33649357e+00],
       [ 1.99712653e-02],
       [ 6.14640611e-01],
       [ 1.61492257e+00],
       [ 1.06150197e+00],
       [ 6.52451957e-01],
       [-1.32405020e+00],
       [ 1.59773560e+00],
       [ 1.56336165e+00],
       [-7.84379179e-01],
       [ 1.17837340e+00],
       [ 7.83072969e-01],
       [ 3.53398586e-01],
       [ 1.17493601e+00],
       [ 6.62764142e-01],
       [-8.35940105e-01],
       [-4.33764883e-01],
       [ 1.14743685e+00],
       [ 1.34336836e+00],
       [-1.20717877e+00],
       [ 2.68460554e-02],
       [ 7.59011204e-01],
       [-1.22436575e+00],
       [ 2.81213290e-01],
       [-9.04688006e-01],
       [-1.79397648e-01],
       [-4.50951858e-01],
       [-1.17624222e+00],
       [-1.40654769e+00],
       [ 8.38071290e-01],
       [-1.33779978e+00],
       [-8.22190525e-01],
       [-5.90888211e-02],
       [ 7.04012883e-01],
       [ 2.46839339e-01],
       [ 6.22168506e-03],
       [ 1.32618139e+00],
       [-1.17624222e+00],
       [ 1.01337844e+00],
       [-5.47198920e-01],
       [-9.45936747e-01],
       [ 1.16806122e+00],
       [-3.13456056e-01],
       [-9.76873303e-01],
       [ 1.25399609e+00],
       [-9.59686327e-01],
       [-7.98128760e-01],
       [-3.89078747e-01],
       [-2.13771599e-01],
       [-1.14087142e-01],
       [-7.15631278e-01],
       [ 1.63898434e+00],
       [ 5.66517080e-01],
       [ 8.24321710e-01],
       [ 6.83388512e-01],
       [-1.07212352e-01],
       [-6.64070352e-01],
       [-3.85641352e-01],
       [ 4.05956357e-02],
       [ 1.55648686e+00],
       [ 1.15087424e+00],
       [-7.63754809e-01],
       [ 1.02468747e-01],
       [ 9.13693982e-01],
       [-7.50005229e-01],
       [ 9.85879278e-01],
       [-1.11093171e+00],
       [ 6.38702377e-01],
       [-1.65404013e+00],
       [ 1.39492929e+00],
       [-5.02512784e-01],
       [ 1.26530512e-01],
       [ 1.05118978e+00],
       [ 1.35711794e+00],
       [-6.46883377e-01],
       [ 1.43961543e+00],
       [-4.37202278e-01],
       [-2.03459414e-01],
       [ 1.47398938e+00],
       [ 9.30880957e-01],
       [-1.00437246e+00],
       [ 1.60461039e+00],
       [ 4.32458673e-01],
       [-1.45810861e+00],
       [-8.97813216e-01],
       [ 1.49117635e+00],
       [ 5.04643969e-01],
       [-1.00337562e-01],
       [ 9.24006167e-01],
       [-1.21405356e+00],
       [-5.30011945e-01],
       [-9.01250611e-01],
       [ 1.60461039e+00],
       [ 4.46208253e-01],
       [-3.13456056e-01],
       [ 1.44305282e+00],
       [-6.09072031e-01],
       [ 1.14056206e+00],
       [ 1.43961543e+00],
       [ 1.58742341e+00],
       [ 9.61817512e-01],
       [-1.68153929e+00],
       [-1.29311365e+00],
       [-9.63123723e-01],
       [ 6.18078006e-01],
       [-1.29655104e+00],
       [ 2.50276734e-01],
       [-1.71935064e+00],
       [-4.53392409e-02],
       [ 1.39492929e+00],
       [-1.44435903e+00],
       [ 1.32274399e+00],
       [ 4.87456994e-01],
       [-6.57195562e-01],
       [ 7.49695863e-02],
       [ 2.22777574e-01],
       [-1.04218381e+00],
       [-1.48461093e-01],
       [-5.12824969e-01],
       [-2.03459414e-01],
       [ 7.49695863e-02],
       [ 4.22146488e-01],
       [-1.48904517e+00],
       [ 6.52451957e-01],
       [ 1.61148518e+00],
       [ 1.02369062e+00],
       [-1.22436575e+00],
       [ 7.45261623e-01],
       [ 2.02153204e-01],
       [ 3.08712451e-01],
       [-1.70903845e+00],
       [ 7.28074648e-01],
       [ 2.74338500e-01],
       [-6.81257327e-01],
       [-9.42499352e-01],
       [ 5.66517080e-01],
       [-1.66091492e+00],
       [ 4.59957833e-01],
       [ 1.88403623e-01],
       [-1.13499348e+00],
       [ 1.48086417e+00],
       [ 1.05118978e+00],
       [ 4.29021278e-01],
       [ 2.70901105e-01],
       [-1.71935064e+00],
       [ 2.26214969e-01],
       [-1.72278803e+00],
       [-8.01566155e-01],
       [ 9.61817512e-01],
       [ 1.11650029e+00],
       [-1.09652902e-02],
       [-3.75329167e-01],
       [ 1.04431499e+00],
       [ 2.29652364e-01],
       [-3.85641352e-01],
       [ 9.03381796e-01],
       [-5.74698080e-01],
       [ 1.16218327e-01],
       [-1.62310357e+00],
       [ 7.00575488e-01],
       [ 5.18393549e-01],
       [-5.85010266e-01],
       [-5.98759846e-01],
       [-1.01812204e+00],
       [-1.59904181e+00],
       [ 1.21962214e+00],
       [ 1.45680240e+00],
       [-5.81572871e-01],
       [ 1.13368727e+00],
       [-6.46883377e-01],
       [ 1.34336836e+00],
       [-1.07999515e+00],
       [-1.43748424e+00],
       [ 5.77826110e-02],
       [ 1.25743349e+00],
       [ 7.84069814e-02],
       [-8.25627920e-01],
       [ 1.62179736e+00],
       [ 1.51867551e+00],
       [ 1.36842697e-01],
       [-7.84379179e-01],
       [ 8.17446920e-01],
       [ 1.04775239e+00],
       [-1.48560777e+00],
       [ 1.03400281e+00],
       [-1.63341576e+00],
       [-1.89709833e-01],
       [ 2.09027994e-01],
       [ 1.45336501e+00],
       [-6.09072031e-01],
       [ 1.56336165e+00]])

In [13]:
from sklearn.linear_model import Ridge

ridge = Ridge(alpha=1.0)
ridge.fit(kx_train, y_train)

print("R²:", ridge.score(kx_test, y_test))

R²: 0.6948262112781812

In [14]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [15]:
y_pred=lr.predict(x_test)
y_pred

array([87.59143866, 70.9696744 , 86.54321929, 81.0026312 , 75.16255187,
       76.85966894, 75.61178874, 62.63383467, 63.13298675, 77.60839706,
       74.86306062, 42.31834502, 77.75814269, 69.62196379, 65.67866236,
       41.32004086, 87.29194741, 49.90545664, 68.22433796, 75.01280625,
       46.86062895, 42.36826023, 79.50517496, 68.62365963, 69.7217942 ,
       48.75740685, 57.29290742, 59.83858302, 57.44265304, 84.54661097,
       57.29290742, 51.40291287, 71.26916565, 43.56622522, 50.25486309,
       57.193077  , 75.06272145, 58.74044845, 80.55339433, 64.7302734 ,
       85.04576305, 49.60596539, 81.65152891, 49.35638935, 86.6430497 ,
       52.55096266, 46.21173125, 79.25559892, 67.2260338 , 88.24033636,
       71.31908086, 53.84875807, 73.41551959, 63.73196924, 48.70749164,
       62.13468259, 43.56622522, 45.71257917, 46.41139208, 64.33095174,
       64.43078216, 74.41382375, 62.13468259, 48.4579156 , 87.19211699,
       87.19211699, 86.39347366, 52.85045391, 73.21585876, 85.44508471,
       67.67527067, 78.65661643, 49.15672852, 77.70822748, 43.06707314,
       53.64909723, 83.69805243, 81.10246162, 67.87493151, 55.74553597,
       64.63044299, 85.79449117, 84.69635659, 78.85627726, 75.41212791,
       54.54757098, 40.37165191, 63.93163008, 80.15407267, 83.09906994,
       70.17103107, 59.58900698, 41.36995607, 46.61105291, 55.14655347,
       61.38595447, 73.51535001, 89.38838614, 45.11359667, 40.02224546,
       63.38256279, 71.01958961, 46.81071374, 68.77340525, 71.86814814,
       64.83010382, 87.34186262, 72.8165371 , 70.67018315, 65.3292559 ,
       58.49087241, 85.69466075, 84.04745889, 66.62705131, 80.75305516,
       70.17103107, 86.39347366, 51.65248891, 43.31664918, 80.70313996,
       55.74553597, 66.27764485, 55.84536638, 76.41043207, 43.86571647,
       58.69053324, 51.60257371, 71.46882648, 83.54830681, 86.29364325,
       74.01450209, 76.95949936, 49.45621976, 51.95198016, 73.86475646,
       56.89358575, 69.32247254, 40.67114316, 43.66605564, 78.30720997,
       54.49765577, 84.99584784, 86.14389762, 81.70144412, 72.66679147,
       78.05763393, 44.91393584, 85.994152  , 64.23112132, 63.432478  ,
       81.95102016, 67.02637297, 65.87832319, 62.88341071, 71.66848731,
       72.71670668, 67.2260338 , 40.22190629, 82.30042661, 76.56017769,
       64.97984944, 51.80223454, 80.20398788, 42.8174971 , 56.09494242,
       54.29799494, 45.61274875, 47.01037457, 50.55435434, 82.35034182,
       62.1845978 , 45.06368146, 79.50517496, 41.02054962, 85.39516951,
       49.00698289, 84.0973741 , 72.51704585, 58.29121158, 42.06876898,
       41.96893857, 49.00698289, 58.14146595, 71.16933523, 63.98154528,
       46.86062895, 62.03485217, 76.80975373, 82.69974827, 64.92993424,
       83.79788285, 63.18290196, 86.79279533, 86.09398242, 79.25559892,
       66.47730568, 42.71766669, 51.20325204, 80.50347912, 61.28612405,
       77.25899061, 74.16424771, 79.95441184, 66.62705131, 77.00941457,
       71.21925044, 79.30551413, 40.17199108, 79.1058533 , 56.29460326,
       80.50347912, 40.2718215 , 89.38838614, 55.99511201, 84.94593263,
       43.01715794, 75.3622127 , 74.1143325 , 60.98663281, 83.24881556,
       85.54491513, 85.59483034, 85.24542388, 51.90206495, 46.41139208,
       55.69562076, 88.98906448, 52.90036911, 70.02128545, 60.9367176 ,
       74.713315  , 79.90449663, 42.01885378, 46.96045937, 57.44265304,
       76.85966894, 64.48069736, 46.06198562, 72.36730022, 59.78866781,
       50.05520226, 52.00189537, 48.20833956, 74.66339979, 62.13468259,
       80.65322475, 81.35203766, 42.61783627, 86.24372804, 64.92993424,
       61.33603926, 75.21246708, 49.45621976, 65.72857756, 68.62365963,
       63.68205404, 47.60935707, 49.80562622, 63.18290196, 53.10002995,
       64.63044299, 45.06368146, 45.86232479, 75.71161916, 68.02467713,
       44.01546209, 78.00771873, 63.58222362, 56.24468805, 47.35978103,
       50.953676  , 75.76153437, 73.91467167, 86.5931345 , 52.50104745,
       68.67357483, 49.35638935, 72.96628272, 81.15237683, 63.73196924,
       67.47560984, 56.64400971, 87.74118428, 41.32004086, 78.70653164,
       89.33847094, 86.89262574, 79.55509017, 41.27012566, 46.81071374,
       64.0813757 , 41.76927774, 87.49160824, 44.0653773 , 64.97984944,
       44.91393584, 56.49426409, 45.56283354, 43.81580126, 43.51631001,
       71.46882648, 39.97233025, 47.1601202 , 50.50443913, 83.99754368,
       73.11602834, 77.8579731 , 54.74723181, 40.87080399, 84.39686535,
       65.27934069, 73.91467167, 88.43999719, 80.40364871, 74.46373896,
       45.76249437, 88.19042115, 87.69126907, 53.59918203, 82.10076578,
       76.36051686, 70.12111587, 82.05085057, 74.61348458, 52.85045391,
       58.69053324, 81.65152891, 84.49669576, 47.45961144, 65.37917111,
       76.01111041, 47.21003541, 69.0728965 , 51.85214975, 62.38425863,
       58.4409572 , 47.90884832, 44.56452938, 77.15916019, 45.56283354,
       53.05011474, 64.13129091, 75.21246708, 68.57374442, 65.07967986,
       84.24711972, 47.90884832, 79.7048358 , 57.04333138, 51.25316725,
       81.95102016, 60.43756552, 50.80393038, 83.19890035, 51.05350642,
       53.39952119, 59.33943094, 61.88510655, 63.33264758, 54.59748619,
       88.78940365, 73.21585876, 76.95949936, 74.91297583, 63.432478  ,
       55.3462143 , 59.38934615, 65.57883194, 87.59143866, 81.70144412,
       53.89867327, 66.47730568, 78.25729476, 54.09833411, 79.30551413,
       48.85723727, 74.26407813, 40.97063441, 85.24542388, 57.69222908,
       66.82671214, 80.25390308, 84.69635659, 55.59579034, 85.89432158,
       58.64061803, 62.03485217, 86.39347366, 78.5068708 , 50.40460872,
       88.29025157, 71.26916565, 43.81580126, 51.95198016, 86.6430497 ,
       72.31738502, 63.53230841, 78.40704039, 47.35978103, 57.29290742,
       51.90206495, 88.29025157, 71.46882648, 60.43756552, 85.94423679,
       56.14485763, 81.55169849, 85.89432158, 88.04067553, 78.95610768,
       40.57131274, 46.21173125, 51.00359121, 73.96458688, 46.16181604,
       68.62365963, 40.02224546, 64.33095174, 85.24542388, 44.01546209,
       84.19720451, 72.06780898, 55.44604472, 66.07798402, 68.22433796,
       49.85554143, 62.8334955 , 57.54248346, 62.03485217, 66.07798402,
       71.11942002, 43.36656439, 74.46373896, 88.39008198, 79.85458142,
       47.21003541, 75.81144957, 67.92484671, 69.47221816, 40.17199108,
       75.56187353, 68.97306608, 55.09663826, 51.30308246, 73.21585876,
       40.87080399, 71.66848731, 67.72518588, 48.50783081, 86.49330408,
       80.25390308, 71.21925044, 68.92315087, 40.02224546, 68.27425317,
       39.97233025, 53.34960599, 78.95610768, 81.20229204, 64.83010382,
       59.53909177, 80.15407267, 68.32416838, 59.38934615, 78.10754914,
       56.64400971, 66.67696651, 41.41987128, 75.16255187, 72.51704585,
       56.49426409, 56.29460326, 50.20494788, 41.76927774, 82.69974827,
       86.14389762, 56.5441793 , 81.45186808, 55.59579034, 84.49669576,
       49.30647414, 44.11529251, 65.82840798, 83.24881556, 66.12789923,
       53.00019953, 88.53982761, 87.04237137, 66.97645776, 53.59918203,
       76.85966894, 80.20398788, 43.4164796 , 80.00432704, 41.27012566,
       62.23451301, 68.02467713, 86.09398242, 56.14485763, 87.69126907])

In [16]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.6948382641132321