In [1]:
import pandas as pd

In [2]:
b=pd.read_csv("badminton_dataset.csv")

In [3]:
b.isnull().sum()

Outlook           0
Temperature       0
Humidity          0
Wind              0
Play_Badminton    0
dtype: int64

In [4]:
b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Outlook         36 non-null     object
 1   Temperature     36 non-null     object
 2   Humidity        36 non-null     object
 3   Wind            36 non-null     object
 4   Play_Badminton  36 non-null     object
dtypes: object(5)
memory usage: 1.5+ KB

In [5]:
b.describe()

         Outlook Temperature Humidity  Wind Play_Badminton
count         36          36       36    36             36
unique         3           3        2     2              2
top     Overcast        Cool     High  Weak             No
freq          12          12       18    18             24

In [6]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
for i in b.columns:
    if b[i].dtype=="object":
        b[i]=l.fit_transform(b[i])

In [7]:
b.head()

   Outlook  Temperature  Humidity  Wind  Play_Badminton
0        0            0         0     1               1
1        2            2         1     0               0
2        1            2         1     0               0
3        2            0         0     1               1
4        2            0         0     0               0

In [8]:
x=b[["Outlook","Temperature","Humidity","Wind"]]
y=b["Play_Badminton"]

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train

    Outlook  Temperature  Humidity  Wind
8         2            1         0     0
17        2            1         0     1
9         2            1         1     0
34        2            2         1     1
0         0            0         0     1
4         2            0         0     0
29        1            2         0     0
15        0            0         1     0
19        0            0         0     0
5         2            2         0     0
11        0            1         0     0
1         2            2         1     0
24        0            0         1     1
2         1            2         1     0
33        1            1         1     1
3         2            0         0     1
32        2            0         1     0
23        1            2         0     1
27        0            1         1     1
10        0            2         0     0
22        2            0         1     1
18        1            1         0     1
25        1            0         1     1
6         1            0         1     0
20        1            1         1     0
7         1            0         0     0
14        2            1         1     1
28        0            2         0     1

In [12]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train, y_train)

MultinomialNB()

In [13]:
y_pred=model.predict(x_test)
y_pred

array([0, 0, 0, 1, 1, 0, 0, 0])

In [14]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.625
[[4 1]
 [2 1]]
              precision    recall  f1-score   support

           0       0.67      0.80      0.73         5
           1       0.50      0.33      0.40         3

    accuracy                           0.62         8
   macro avg       0.58      0.57      0.56         8
weighted avg       0.60      0.62      0.60         8