In [1]:
import pandas as pd

In [2]:
a=pd.read_csv("insurance.csv")
a

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [3]:
a= pd.get_dummies(a, columns=['region'], drop_first=True)

In [4]:
a.isnull().sum()

age                 0
sex                 0
bmi                 0
children            0
smoker              0
charges             0
region_northwest    0
region_southeast    0
region_southwest    0
dtype: int64

In [5]:
a['sex'] = a['sex'].map({'male': 1, 'female': 0})
a['smoker'] = a['smoker'].map({'yes': 1, 'no': 0})

In [6]:
a.describe()

,age,sex,bmi,children,smoker,charges
count,1338.000000,1338.000000,1338.000000,1338.000000,1338.000000,1338.000000
mean,39.207025,0.505232,30.663397,1.094918,0.204783,13270.422265
std,14.049960,0.500160,6.098187,1.205493,0.403694,12110.011237
min,18.000000,0.000000,15.960000,0.000000,0.000000,1121.873900
25%,27.000000,0.000000,26.296250,0.000000,0.000000,4740.287150
50%,39.000000,1.000000,30.400000,1.000000,0.000000,9382.033000
75%,51.000000,1.000000,34.693750,2.000000,0.000000,16639.912515
max,64.000000,1.000000,53.130000,5.000000,1.000000,63770.428010

In [7]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               1338 non-null   int64
 1   sex               1338 non-null   int64
 2   bmi               1338 non-null   float64
 3   children          1338 non-null   int64
 4   smoker            1338 non-null   int64
 5   charges           1338 non-null   float64
 6   region_northwest  1338 non-null   bool
 7   region_southeast  1338 non-null   bool
 8   region_southwest  1338 non-null   bool
dtypes: bool(3), float64(2), int64(4)
memory usage: 66.8 KB

In [8]:
a.head()

,age,sex,bmi,children,smoker,charges,region_northwest,region_southeast,region_southwest
0,19,0,27.900,0,1,16884.92400,False,False,True
1,18,1,33.770,1,0,1725.55230,False,True,False
2,28,1,33.000,3,0,4449.46200,False,True,False
3,33,1,22.705,0,0,21984.47061,True,False,False
4,32,1,28.880,0,0,3866.85520,True,False,False

In [9]:
x=a[['age','bmi','children','region_northwest','region_southeast','region_southwest','smoker','sex']]
y=a['charges']
x

,age,bmi,children,region_northwest,region_southeast,region_southwest,smoker,sex
0,19,27.900,0,False,False,True,1,0
1,18,33.770,1,False,True,False,0,1
2,28,33.000,3,False,True,False,0,1
3,33,22.705,0,True,False,False,0,1
4,32,28.880,0,True,False,False,0,1
...,...,...,...,...,...,...,...,...
1333,50,30.970,3,True,False,False,0,1
1334,18,31.920,0,False,False,False,0,0
1335,18,36.850,0,False,True,False,0,0
1336,21,25.800,0,False,False,True,0,0
1337,61,29.070,0,True,False,False,1,0

In [10]:
#model selection
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
x_train

,age,bmi,children,region_northwest,region_southeast,region_southwest,smoker,sex
332,61,31.160,0,True,False,False,0,0
355,46,27.600,0,False,False,True,0,1
138,54,31.900,3,False,True,False,0,0
381,55,30.685,0,False,False,False,1,1
292,25,45.540,2,False,True,False,1,1
...,...,...,...,...,...,...,...,...
1095,18,31.350,4,False,False,False,0,0
1130,39,23.870,5,False,True,False,0,0
1294,58,25.175,0,False,False,False,0,1
860,37,47.600,2,False,False,True,1,0
1126,55,29.900,0,False,False,True,0,1

In [11]:
x_test

,age,bmi,children,region_northwest,region_southeast,region_southwest,smoker,sex
764,45,25.175,2,False,False,False,0,0
887,36,30.020,0,True,False,False,0,0
890,64,26.885,0,True,False,False,1,0
1293,46,25.745,3,True,False,False,0,1
259,19,31.920,0,True,False,False,1,1
...,...,...,...,...,...,...,...,...
701,50,44.745,0,False,False,False,0,0
672,36,29.700,0,False,True,False,0,1
1163,18,28.215,0,False,False,False,0,0
1103,58,36.080,0,False,True,False,0,1
1295,20,22.000,1,False,False,True,0,1

In [12]:
#linear regression
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [13]:
y_pred=lr.predict(x_test)
y_pred

array([ 9.01636753e+03,  7.01997635e+03,  3.68708343e+04,  9.51853774e+03,
        2.69740308e+04,  1.10808462e+04, -4.06177600e+01,  1.71922331e+04,
        9.74950536e+02,  1.13299594e+04,  2.80574861e+04,  9.47838799e+03,
        4.98095281e+03,  3.84564701e+04,  4.03433327e+04,  3.71038753e+04,
        1.51982019e+04,  3.57689693e+04,  8.88568387e+03,  3.13835989e+04,
        3.79641903e+03,  1.02628964e+04,  2.37593679e+03,  7.26280819e+03,
        1.12875675e+04,  1.31383480e+04,  1.46241614e+04,  6.07324604e+03,
        1.00361537e+04,  1.97927814e+03,  9.07103928e+03,  1.31369887e+04,
        4.30868680e+03,  3.21105955e+03,  4.48957162e+03,  1.33774493e+04,
        1.82221028e+03,  8.79191682e+03,  3.31981518e+04,  3.25005781e+04,
        3.76368816e+03,  4.35479656e+03,  1.42473276e+04,  1.15436019e+04,
        8.70433805e+03,  1.22401028e+04,  5.20831471e+03,  2.98293172e+03,
        3.54465532e+04,  9.10285846e+03,  1.57820945e+04,  2.13473894e+03,
        1.24668220e+04,  1.54938571e+03,  1.34053719e+04,  1.28473334e+04,
        4.45292570e+03,  3.22437514e+04,  1.34037537e+04,  1.30759280e+04,
        1.42566593e+04,  1.03870794e+04,  1.66115344e+04,  7.67924983e+03,
        1.19859772e+04,  3.92843534e+03,  2.65835119e+04,  1.08308191e+04,
        1.95128291e+03,  6.33488049e+03,  1.10112514e+04,  1.17636262e+04,
        1.08263871e+04,  9.08234702e+03,  1.19604601e+04,  6.50105143e+03,
        7.42735409e+03,  1.07211916e+04,  6.33354759e+03,  8.69733988e+03,
        3.61488505e+03,  3.68736945e+04,  6.30687909e+03,  3.09068874e+04,
        3.49064234e+04,  3.55280239e+04,  6.88613550e+03,  1.30506683e+04,
        9.92931617e+03,  1.46956125e+04,  1.79662926e+04,  3.50278076e+04,
        3.30746710e+04,  6.32482249e+03,  3.19085861e+04,  9.60073983e+03,
        2.92677441e+04,  3.39493394e+03,  2.81321269e+04,  5.80676746e+03,
        5.31282926e+03,  1.74776460e+03,  1.15200454e+04,  1.53050498e+04,
        1.19233534e+04,  4.16886626e+03,  9.81313523e+03,  3.15291378e+04,
       -7.47759770e+01,  3.25392808e+04,  3.31798546e+03,  1.02123570e+04,
        1.45082163e+04,  3.16997266e+04,  1.15930594e+04,  3.96851082e+03,
        1.33856566e+04,  3.17279010e+04,  7.91762470e+03,  3.22395489e+03,
        8.53540558e+03,  1.07379420e+04,  1.54527618e+04,  5.54280724e+03,
        3.62333901e+03,  1.02353762e+04,  1.07499966e+04,  1.13664096e+04,
        1.43531092e+04,  7.39239715e+03,  5.11044589e+03,  9.15211414e+03,
        9.16049984e+03,  1.27422989e+04,  8.33444005e+03,  1.55896092e+04,
        8.65087064e+03,  3.18745705e+04,  3.58544577e+04,  3.16617444e+04,
        5.92615317e+03,  1.27853573e+04,  5.91188204e+03,  1.46675118e+04,
        2.27316618e+03,  3.30166968e+04,  6.29418942e+03,  4.95310907e+03,
        1.44325801e+04,  7.01569740e+03,  3.87492720e+04,  2.96019320e+03,
        5.81725421e+03,  3.18785754e+04,  1.16459127e+04,  8.71329062e+03,
        1.51346583e+04,  9.60753792e+03,  2.68003840e+04,  3.36706354e+04,
        1.47334585e+04,  1.51047070e+03,  1.33077834e+04,  2.29238567e+03,
        5.49596778e+03,  1.15549473e+04,  3.99435773e+04,  3.65333329e+04,
        3.42186307e+04,  3.80401582e+03,  7.35909889e+03,  8.65388710e+03,
        1.28040524e+04,  4.81713793e+03,  1.90362292e+03,  3.19590456e+04,
        2.50622553e+04,  1.76066342e+04,  2.61755399e+04,  1.01206885e+04,
        3.73947874e+04, -5.95739589e+02,  6.77709620e+03,  7.76609078e+03,
        4.43645530e+03,  5.04452875e+03,  6.07417881e+03,  4.20334246e+03,
        1.51726032e+04,  1.12607758e+04,  7.03115820e+03,  2.50525091e+03,
        1.46223072e+03,  3.20466562e+04,  1.65083439e+04,  1.18789362e+04,
        1.07957066e+03,  1.26607400e+04,  1.51086620e+03,  8.69657642e+03,
        1.68902224e+03,  3.40058138e+04,  1.08756889e+04,  2.56974017e+03,
        2.52981537e+04,  2.59738976e+04,  9.52339115e+03,  1.58473036e+03,
        1.33107441e+04,  9.13519256e+02,  1.04715423e+04,  1.03398989e+04,
        1.72658883e+04,  2.66233875e+04,  6.77219998e+03,  5.20991396e+03,
        5.56558337e+03,  1.30540226e+04,  1.08915693e+04,  8.16068430e+03,
        5.08929190e+03,  1.25297793e+04,  1.39348614e+04,  3.57516495e+04,
        4.19584669e+03,  2.87579313e+04, -1.14816280e+03,  2.88161740e+03,
        1.09878160e+04,  1.56242628e+04,  5.10433431e+03,  6.76301444e+03,
        3.70867236e+03,  3.13682722e+04,  7.12374983e+03,  1.24206482e+04,
        5.65837260e+03,  9.67672163e+03,  3.61915157e+04,  4.29099794e+03,
        9.70105983e+03,  3.12449368e+04,  5.70357956e+03,  4.31220132e+03,
        9.92286457e+02,  4.87642666e+03,  4.45920549e+03,  6.58071354e+03,
        1.86745012e+04, -1.69255225e+03,  2.25329636e+03,  1.08451735e+04,
        3.01782548e+03,  1.02761615e+04,  3.63182475e+03,  4.85687937e+03,
        1.25657503e+04,  6.29493049e+03,  8.39003640e+03,  7.63851451e+03,
        8.87347523e+03,  1.04366607e+04,  2.76138998e+04,  3.90930962e+04,
        1.17741240e+04,  7.86236646e+03,  4.09351452e+04,  1.23825919e+04,
        6.96769121e+03,  8.39240771e+03,  8.91633322e+03,  1.09407283e+04,
        1.00125242e+04,  1.76907551e+04,  9.26683559e+02,  2.35867374e+04,
        1.29922761e+04,  3.33839370e+04,  5.28567464e+03,  1.31828238e+04,
        1.03836902e+04,  1.80715482e+04,  9.94657758e+03,  1.15453067e+04,
        3.23413107e+04,  3.41161034e+03,  1.35695874e+04,  3.94082337e+04,
        5.63940644e+03,  6.20614527e+03,  3.46648946e+03,  1.15027340e+04,
        2.54222822e+04,  1.43993856e+04,  9.12076342e+03,  1.02268595e+04,
        1.34991650e+04,  8.25909265e+02,  2.19043856e+03,  3.06679851e+04,
        3.00633206e+04,  1.36495385e+04,  3.62504384e+03,  2.53430882e+04,
        1.33871712e+04,  3.06238167e+04,  3.52503711e+03,  3.89322157e+04,
        1.11916611e+04,  4.71456861e+03,  6.78218447e+03,  2.36501751e+03,
        2.58238275e+04,  1.44838321e+04,  4.96503755e+02,  1.28284375e+04,
        1.26451381e+04,  1.50224474e+04,  3.49844233e+04,  1.44199994e+04,
        3.14508055e+04,  1.00596099e+04,  1.84250838e+04,  6.02322900e+03,
        8.77054459e+03,  9.42475332e+03,  1.52623599e+04,  9.10147364e+03,
        8.57703747e+03,  1.52538666e+04,  1.29162371e+04,  1.50507091e+04,
        7.55688638e+03,  2.59073220e+04,  9.17887997e+03,  1.76843257e+03,
        4.06914171e+03,  1.44063918e+04,  3.56818824e+04,  9.65101980e+03,
        1.27491470e+04,  5.36425043e+03,  4.90925822e+03,  3.96001083e+03,
        2.83671248e+03,  8.96711387e+03,  6.97687982e+03,  2.29664368e+03,
        1.32191990e+04,  8.83743782e+03,  5.95734540e+03,  6.77014819e+02,
        9.45177386e+03,  4.78553948e+03,  3.30846888e+04,  2.84093679e+04,
        3.68889748e+04,  5.66951803e+03,  8.49155880e+03,  8.19133366e+03,
        3.54425195e+03,  3.17311679e+04,  7.22097249e+03,  2.81725993e+04,
        3.62070046e+04,  6.92517056e+03,  1.30191895e+04,  9.89787484e+03,
        8.25555525e+03,  1.29121247e+04,  3.02357185e+04,  1.73698010e+04,
        1.20163203e+04,  3.92606402e+03, -1.31795195e+03,  1.23019494e+04,
        3.09216571e+04,  1.29541180e+04,  1.13530730e+04,  7.95364590e+03,
        3.70314484e+03,  7.16459184e+03,  7.19704321e+03,  1.07380621e+04,
        3.36978089e+04,  3.92682564e+04,  1.19732353e+04,  8.28169782e+03,
        1.65740731e+04,  1.57632625e+04,  9.68911634e+03,  9.40128897e+03,
        8.88121990e+03,  2.71557719e+03,  1.01799538e+04,  3.69233650e+03,
        1.06473891e+04,  1.63027222e+04,  6.52910373e+03,  2.17378934e+03,
        1.45036622e+04,  1.30534757e+02])

In [16]:
#accuracy measure
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.7696118054369012